const routes = {
    explore: "/",
    zingChart: '/zing-chart',
    zingChartVietNam: '/zing-chart/song-viet-nam',
    zingChartUsUk: '/zing-chart/song-us-uk',
    zingChartKpop: '/zing-chart/song-Kpop',
    radio: '/radio',
    library: '/library',
    releaseNew: '/moi-phat-hanh',
    hub: '/hub',
    hubChild: '/hub',
    top100: '/top100',
    login: '/login',
    register: '/register',
    playlistNew: '/playlist-new',
    newReleaseSong: '/new-release/song',
    newReleaseAlbum: '/new-release/album',
    album: '/album',

    myMusicHistory: '/mymusic/history',
    myMusicSongFavourite: '/mymusic/song/favourite',
    myMusicLibraryPlaylist: '/mymusic/library/playlist',
    myMusicAlbum: '/mymusic/album',
    myMusicSongUpload: '/mymusic/song/upload',

    adminAnalytics: '/admin/menu/dashboards/analytics',
    adminChartArea: '/admin/menu/dashboards/chart-area',

    adminExplore: '/admin/menu/pages/explore',
    adminHub: '/admin/menu/pages/hub',

    adminMailBox: '/admin/menu/application/mailbox',
    adminChat: '/admin/menu/application/chat',
    adminSection: '/admin/menu/application/section',

    adminArtist: '/admin/manage/artist/list',
    adminArtistCreate: '/admin/manage/artist/create',
    adminArtistUpdate: '/admin/manage/artist/update',
    adminSong: '/admin/manage/song/list',
    adminSongCreate: '/admin/manage/song/create',
    adminSongUpdate: '/admin/manage/song/update',
    adminPlaylist: '/admin/manage/playlist/list',
    adminPlaylistCreate: '/admin/manage/playlist/create',
    adminPlaylistUpdate: '/admin/manage/playlist/update',
    adminAlbum: '/admin/manage/album/list',
    adminAlbumCreate: '/admin/manage/album/create',
    adminAlbumUpdate: '/admin/manage/album/update',
    adminUser: '/admin/manage/user/list',
    adminUserCreate: '/admin/manage/user/create',
    adminUserUpdate: '/admin/manage/user/update',
    adminGenre: '/admin/manage/genre/list',
    adminGenreCreate: '/admin/manage/genre/create',
    adminGenreUpdate: '/admin/manage/genre/update',
    adminPartner: '/admin/manage/partner/list',
    adminPartnerCreate: '/admin/manage/partner/create',
    adminPartnerUpdate: '/admin/manage/partner/update',
    adminWeekchart: '/admin/manage/weekchart/list',
    adminWeekchartCreate: '/admin/manage/weekchart/create',
    adminWeekchartUpdate: '/admin/manage/weekchart/update',
}

export default routes